"""add seminar joint groups

Revision ID: 496c24efe3d1
Revises: d72867c83af0
Create Date: 2026-07-24 14:01:43.964158

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "496c24efe3d1"
down_revision: Union[str, Sequence[str], None] = "d72867c83af0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seminar_joint_groups",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("seminars", sa.Column("joint_group_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_seminars_joint_group",
        "seminars",
        "seminar_joint_groups",
        ["joint_group_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_seminars_joint_group", "seminars", type_="foreignkey")
    op.drop_column("seminars", "joint_group_id")
    op.drop_table("seminar_joint_groups")
    # ### end Alembic commands ###
