"""drop unique constraint on recruitment_terms academic_year

Revision ID: 55ad85bff0a6
Revises: 9f93b87e3175
Create Date: 2026-07-06 13:34:16.989245

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55ad85bff0a6"
down_revision: Union[str, Sequence[str], None] = "9f93b87e3175"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("recruitment_terms_academic_year_key"), "recruitment_terms", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("recruitment_terms_academic_year_key"),
        "recruitment_terms",
        ["academic_year"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
