"""add research tags

Revision ID: 7dc6130962c8
Revises: 55ad85bff0a6
Create Date: 2026-07-06 22:34:34.603554

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7dc6130962c8"
down_revision: Union[str, Sequence[str], None] = "55ad85bff0a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# 初期の研究分野タグ(運営が今後マスタを追加/編集する運用は別途検討)。
# 大分類ごとにグルーピングし、この一覧の並び順どおりに表示する
# (名前順だとローマ字/カタカナ/漢字が混在して分かりにくいため)。
INITIAL_TAGS: list[tuple[str, list[str]]] = [
    ("AI・機械学習", ["深層学習", "生成AI", "強化学習"]),
    ("データ分析", ["統計解析", "時系列解析", "データ可視化"]),
    ("自然言語処理", ["LLM", "文章解析"]),
    ("画像・映像", ["画像認識", "医療画像"]),
    ("音声・音響", ["音声認識", "音楽情報処理"]),
    ("データベース", ["データベース", "知識ベース"]),
    ("Web・アプリ", ["Web開発", "モバイル開発"]),
    ("セキュリティ", ["暗号", "認証"]),
    ("IoT・組込み", ["センサ", "エッジAI"]),
    ("ロボティクス", ["自律移動", "制御"]),
    ("数理最適化", ["最適化", "組合せ最適化"]),
    ("HCI・UX", ["UI/UX", "ユーザビリティ"]),
    ("VR・AR", ["VR/AR", "VRコンテンツ制作", "メタバース"]),
    ("バイオ・医療", ["医療AI", "ゲノム"]),
    ("社会・経済", ["金融", "マーケティング", "教育"]),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    research_tags = op.create_table(
        "research_tags",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False, server_default=""),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user_interest_tags",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["research_tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "tag_id", name="uq_user_interest_tag"),
    )
    # ### end Alembic commands ###

    rows = []
    sort_order = 0
    for category, tags in INITIAL_TAGS:
        for name in tags:
            rows.append({"name": name, "category": category, "sort_order": sort_order})
            sort_order += 1
    op.bulk_insert(research_tags, rows)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_interest_tags")
    op.drop_table("research_tags")
    # ### end Alembic commands ###
