"""add photo_url to users

Revision ID: 9f93b87e3175
Revises: 0cd69d361388
Create Date: 2026-07-05 16:14:46.074817

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f93b87e3175"
down_revision: Union[str, Sequence[str], None] = "0cd69d361388"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("photo_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "photo_url")
    # ### end Alembic commands ###
