"""add asker notification thread tracking to questions

Revision ID: b4ca663e930a
Revises: 0cd69d361388
Create Date: 2026-07-04 01:00:10.360475

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4ca663e930a"
down_revision: Union[str, Sequence[str], None] = "0cd69d361388"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column("asker_notification_channel_id", sa.String(), nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column("asker_notification_message_ts", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "asker_notification_message_ts")
    op.drop_column("questions", "asker_notification_channel_id")
    # ### end Alembic commands ###
