"""add ai usage counters

Revision ID: bbde17a5a6be
Revises: 496c24efe3d1
Create Date: 2026-07-26 22:50:01.950351

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbde17a5a6be"
down_revision: Union[str, Sequence[str], None] = "496c24efe3d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_usage_counters",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("term_id", sa.UUID(), nullable=True),
        sa.Column(
            "feature",
            sa.Enum(
                "match",
                "consult",
                name="aifeature",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["term_id"], ["recruitment_terms.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "term_id",
            "feature",
            name="uq_ai_usage_user_term_feature",
            postgresql_nulls_not_distinct=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_usage_counters")
    # ### end Alembic commands ###
